T91, T92, T96: Standardize typography
Project-Chirp/chirp-frontend pull request #97
Opened 2024-05-06 00:14 UTC by Dennull

This PR seeks to standardize some of the typography in the app. It closes #91, closes #92, and fixes #96. There are a lot of changes in this PR, but I essentially took a look at what different types of text we were using around the app and mapped them to specific
 variants in `Theme.tsx`. This way, we can just use MUI's `Typography` component and simply specify the `variant` prop whenever we wanted text to look a certain way.

The following variants were made:

- h1 - rarely used but I made it for larger titles like the welcome page or the "select a message" prompt
- h2 - used for the titles at the top of each page (eg. "Timeline" or "Messages")
- h3 - is mainly used for the navbar items, but is also used in a few other places in the app
- subtitle1 - the display name text, which is bolded
- subtitle2 - the username text, which is gray and has a lighter font weight
- body1 - the standard text used throughout the app
- body2 - the exact same as subtitle2 (the username text), but in a smaller font size. It's used for smaller captions like the footer or to display timestamps in the messages

2024-05-11 05:07 UTC, NasihNazeem requested changes
Mostly looks good, I think I just had a few comments but overall app layout is looking so good, well done bro genuinely

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/Messages/ConversationList.tsx
> +    paddingTop: 1,
I think we should keep the padding consistent with the Timeline header title where we do something like 

`padding: 2`

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/Messages/ConversationListItem.tsx
> +    fontSize: 15,
Let's remove this `fontSize`?

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/Messages/ConversationListItem.tsx
> +  username: { flex: "1, 1, auto", fontSize: 15, minWidth: 0 },
Remove `fontSize` again I think

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/NavBar/AccountMenu.tsx
> +          <Typography color="primary" variant="subtitle1" fontSize={15}>
Do we still need this `fontSize`?

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/NavBar/NavItem.tsx
> +        primaryTypographyProps={{ variant: "h3" }}
We should figure out a way to have bold/not bold styling depending on whether this is selected (this should be done within [Navbar styling](https://github.com/Project-Chirp/chirp-frontend/issues/63))

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/SideBar/RelevantUsers.tsx
> +        {/* TODO: Remove this if the post is by the current user */}
Good catch!

2024-05-11 05:07 UTC, NasihNazeem commented on src/components/SideBar/SidebarFooter.tsx
Nothing to add, but can we also remove the `Docs` link from the footer? I think we agreed to remove it in one of the meetings

2024-05-11 05:07 UTC, NasihNazeem commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
Can we make this more bold?

2024-05-15 05:30 UTC, Dennull commented on src/components/Messages/ConversationList.tsx
> +    paddingTop: 1,
The reason the padding is like this is cause I had to take into account the padding of the icon button in the header and the search bar under it. I can make the padding of the others 0 and compensate for it in the header, but at the end of the day it's kinda the same thing

If you'd prefer me to change the padding of the other components and make the header have a `padding: 2` I can, I don't have a strong opinion on it. Let me know if this makes sense or needs more explaining

2024-05-15 05:31 UTC, Dennull commented on src/components/Messages/ConversationListItem.tsx
> +    fontSize: 15,
The display name in the title of the conversation has a font size of 15, so if the username and timestamp have a different font size it looks weird. I think this is a one-off situation so I'm ok with having it be a custom style. What do you think?

2024-05-15 05:32 UTC, Dennull commented on src/components/Messages/ConversationListItem.tsx
> +  username: { flex: "1, 1, auto", fontSize: 15, minWidth: 0 },
See the comment above about the timestamp, the same applies here

2024-05-15 05:32 UTC, Dennull commented on src/components/NavBar/AccountMenu.tsx
> +          <Typography color="primary" variant="subtitle1" fontSize={15}>
Nope, got rid of it!

2024-05-15 05:34 UTC, Dennull commented on src/components/NavBar/NavItem.tsx
> +        primaryTypographyProps={{ variant: "h3" }}
Yeah that would be cool. Maybe the font weight changes a bit. @christopherkinyua maybe take a look at this let us know if you can

2024-05-15 05:34 UTC, Dennull commented on src/components/SideBar/SidebarFooter.tsx
Yup!

2024-05-15 05:35 UTC, Dennull commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
Do you think we should make this one use more bold or make all of the `h3` elements have a bolder font weight?

2024-05-15 07:00 UTC, NasihNazeem commented on src/components/Messages/ConversationList.tsx
> +    paddingTop: 1,
That makes sense, let's leave this as is

2024-05-15 07:05 UTC, NasihNazeem commented on src/components/Messages/ConversationListItem.tsx
> +    fontSize: 15,
Okay yeah that's fair. I looked at some of the other components, and I don't see a need for it elsewhere

2024-05-15 07:10 UTC, NasihNazeem commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
I don't it is necessary in other areas we used `h3` as I like the boldness for the other h3...Just feel like this one feels a bit light

2024-05-15 07:11 UTC, NasihNazeem reviewed
More feedback!

2024-05-15 18:47 UTC, Dennull commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
Ok, I'll make this one bolder

2024-05-15 18:52 UTC, Dennull commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
So do you think I should I also make the title of this page the same boldness? The title of the profile page and the display name both use `h3`, so should they be the same font weight too?

2024-05-15 18:58 UTC, NasihNazeem commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
I think the title is fine, just the display name in the user profile section. It's a nitpick but I think a slight increase in boldness will help the overall look

2024-05-15 19:03 UTC, Dennull commented on src/pages/Profile.tsx
> +                  <Typography variant="h3">
Ok sounds good

2024-05-15 19:24 UTC, NasihNazeem approved these changes

2024-05-15 19:41 UTC, merged